[package]
name = "webassembly-rust-learning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.63"

[lib]
crate-type = ["cdylib"]
path = "lib/lib.rs"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
